//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventorySystemEntities : DbContext
    {
        public InventorySystemEntities()
            : base("name=InventorySystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductPicture> ProductPictures { get; set; }
        public virtual DbSet<ProductStock> ProductStocks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<ProductV> ProductVs { get; set; }
        public virtual DbSet<PO> POes { get; set; }
        public virtual DbSet<PODetail> PODetails { get; set; }
        public virtual DbSet<PODetailV> PODetailVs { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<StockV> StockVs { get; set; }
        public virtual DbSet<ProductQtyV> ProductQtyVs { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerGroup> CustomerGroups { get; set; }
        public virtual DbSet<PaymentTerm> PaymentTerms { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<RawMaterail> RawMaterails { get; set; }
        public virtual DbSet<PoV> PoVs { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
    }
}
