//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoV
    {
        public int POId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string DeliveryAddress { get; set; }
        public string RefNumber { get; set; }
        public string Expr1 { get; set; }
        public string PONumber { get; set; }
        public string TermsOfPayment { get; set; }
    }
}
