//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPicture
    {
        public int ProductPictureId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
