//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductQtyV
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Qty_Purchased { get; set; }
        public Nullable<decimal> Qty_Receiving { get; set; }
        public int Qty_Sales { get; set; }
        public int Qty_Shipment { get; set; }
        public Nullable<decimal> Qty_On_Hand { get; set; }
    }
}
