//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receiving
    {
        public int ReceivingId { get; set; }
        public string GSRNNumber { get; set; }
        public Nullable<int> POId { get; set; }
        public Nullable<System.DateTime> GSRNDate { get; set; }
        public string VendorDONumber { get; set; }
        public string VendorInvoiceNumber { get; set; }
        public Nullable<decimal> TotalInvoice { get; set; }
    }
}
