//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int Id { get; set; }
        public string DONumber { get; set; }
        public Nullable<System.DateTime> DODate { get; set; }
        public Nullable<int> SalesOrderId { get; set; }
        public Nullable<int> CourierId { get; set; }
        public string Installer { get; set; }
        public string Status { get; set; }
        public string TrackingNumber { get; set; }
        public string Description { get; set; }
    }
}
